name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Install pnpm
        run: npm install pnpm
        
      - name: Install Dependencies
        run: pnpm install -r
        
      - name: Build App
        run: pnpm run build
        
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Install pnpm
        run: npm install pnpm
        
      - name: Install Dependencies
        run: pnpm install -r
        
      - name: Lint
        run: pnpm run lint
