name: CI

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install -r

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
