name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install -r

      - name: Update Firebase Config
        run: echo ${{ secrets.FIREBASE_CONFIG }} | base64 -d > src/conifgs/firebase.json

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
