name: CI

on:
  workflow_dispatch:

  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install -r

      - name: Lint
        run: pnpm run lint

      - name: Unit Test Firestore Security Rules
        run: pnpm run test:firestore:ci

      - name: Build
        run: pnpm run build
