name: Deploy

on:
  release:
    types:
      - published
  push:
    branches:
      - 'main'

jobs:
  staging:
    name: Staging
    if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main'
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      environment: Staging
      environment_url: https://stg.remembit.app
    secrets:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  production:
    name: Production
    if: github.event_name == 'release'
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      environment: Production
      environment_url: https://remembit.app
