name: Deploy

on:
  workflow_run:
    workflows: [Release]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    environment:
      name: production
      url: https://remembit.app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install -r

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Deploy
        run: pnpm run deploy -m "Deploying v$(cat package.json | jq -r .version)" --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
