name: Deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Production
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://remembit.app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install -r

      - name: Update Firebase Config
        run: echo ${{secrets.FIREBASE_CONFIG}} | base64 -d > src/conifgs/firebase.json

      - name: Build
        run: pnpm run build

      - name: Deploy
        run: |
          pnpm exec \
            firebase \
              --project ${{ secrets.FIREBASE_PROJECT_ID }} \
              --token ${{ secrets.FIREBASE_TOKEN }} \
            deploy \
              -m "Deploying v$(cat package.json | jq -r .version)"
