name: Deploy

on:
  workflow_call:
    inputs:
      versionTag:
        description: 'Version to deploy'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      versionTag:
        description: 'Version to deploy'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    environment:
      name: production
      url: https://remembit.app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.versionTag }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install -r

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Deploy
        run: |
          pnpm exec \
            firebase \
              --project ${{ secrets.FIREBASE_PROJECT_ID }} \
              --token ${{ secrets.FIREBASE_TOKEN }} \
            deploy \
              -m "Deploying v$(cat package.json | jq -r .version)"
