name: Deploy

on:
  release:
    types:
      - published
  push:
    branches:
      - 'main'

jobs:
  staging:
    name: Staging
    uses: .github/workflows/reusable_deploy.yml
    with:
      environment: Staging
      environment_url: https://stg.remembit.app

  production:
    name: Production
    uses: .github/workflows/reusable_deploy.yml
    with:
      environment: Production
      environment_url: https://remembit.app
