name: reusable_deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      environment_url:
        type: string
        required: true
    secrets:
      FIREBASE_PROJECT_ID:
        required: true
      FIREBASE_TOKEN:
        required: true
      FIREBASE_FUNCTIONS_ENV:
        required: true
      REMEMBIT_ENV:
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment_url }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install -r

      - name: Update Firebase Functions envars
        run: echo ${{ secrets.FIREBASE_FUNCTIONS_ENV }} | base64 -d > functions/.env

      - name: Update Remembit envars
        run: echo ${{ secrets.REMEMBIT_ENV }} | base64 -d > .env

      - name: Build
        run: pnpm run build

      - name: Deploy
        run: |
          pnpm exec \
            firebase \
              --project ${{ secrets.FIREBASE_PROJECT_ID }} \
              --token ${{ secrets.FIREBASE_TOKEN }} \
            deploy
